---
- hosts: localhost
  connection: local
  collections:
    - community.aws
 
  tasks:
  - name: Enabling versioning for S3 bucket
    s3_bucket:
      name: 
      state: 
      public_access:
        block_public_acls: true
        ignore_public_acls: true
        block_public_policy: true
        restrict_public_buckets: true
      versioning: true
      region: 
 
  - name: Enabling logging for S3 bucket
    community.aws.s3_logging:
      name: 
      target_bucket:  
      target_prefix:   
      state: 

  - name: Configuring a lifecycle policy rule on bucket to expire (delete) items with a prefix of /logs/ after 30 days
    s3_lifecycle:
      name: 
      expiration_days: 
      prefix: 
      status: 
      state:
