---
- name: Modify Lambda configurations
  hosts: localhost  
  tasks:
    - name: Update Lambda function configurations
      amazon.aws.lambda:
        name:   
        state: 
        role: 
        region: 
        runtime:   
        description: 
        memory_size:
        handler: 
        environment_variables:
          project: 
          test:  
        tags:
          environment: 
